### PR TITLE
Burczyk/master

### PR DESCRIPTION
**Pull request by baytelman**

### CODE REVIEW

**Comment by burczyk** [comment]
Thanks! Pushed to CocoaPods.

**Comment by baytelman** [comment]
Thanks.... I tried and (of course) I didn't have permissions. Also, it had a BUG which I fixed (it got introduced when I did the un-merge from my other branch). Can you push again 1.2.3?

**Comment by baytelman** [comment]
Did you try the feature???

**Comment by burczyk** [comment]
Yes, I tried it and pushed 1.2.3 to CocoaPods. Can you give me your email so that I can add you to CocoaPods trunk?

**Comment by baytelman** [comment]
felipe DOT baytelman AT gmail

**Comment by burczyk** [comment]
Done. You can remove your email if you want.

**Pull request merged**
